= Nodatime+Mongo (Sandbox)

this project is all about marrying Nodatime to Mongo.

== Features

* C#8 with enforced Nullability
* DateTime (Utc and Local)
* Nodatime
* Mongo 
  * Using `IsUpsert` to add or replace documents if they already exist
* Testcontainers.Net for Mongo Instance

== Usage

. Have docker installed (for Testcontainers)
. Run tests
.. `cd NodatimeMongo.IntTest`
.. `dotnet test`

== Troubleshooting

> The container name mongo is already in use by container <containerId>

The container instance was not shut down properly. Can happen when you debug for example. You need to open your terminal/shell find out the id of your mongo container and shut it down by hand before removing it.

* `docker ps -a` and note the id of your mongo container (f.ex. `75c098b62207f57...`). The first two letters are usually unique (f.ex. `75`) which allows you to do:
* Stop container: `docker stop <containerId>` 
* Remove container: `docker rm <containerId>`

== Further Reading

* link:https://mongodb.github.io/mongo-csharp-driver/2.12/getting_started/quick_tour/[MongoDb Getting Started]
